name: 🚀 timeWise

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    name: 🎉 Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          known_hosts: 'larakey'

      - name: 🚚 Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.DEV_SSH_PORT }} -H ${{ secrets.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Run Deployment Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          command_timeout: 30m
          script: |
            cd /www/wwwroot/hrm.aamarpay.dev
            git stash
            git pull origin dev
            composer install
            php artisan migrate
